%== The difference between this code with Data4SAS.m is to take calendar year into account ==%  

timedepvar = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FoFData4SAS.xlsx');
    % timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    % This dataset is generated by using AliveDistanceLiquidation_FoF.m
 %-- Liquidated Funds Drop Reasons
 DropReason = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FundDropReasons.xlsx','DropReasons');
    % DropReason = [DropFundID DropReasonID]
    %-- Find EventID 0 = Alive; 1 = Liquidated
 FundID = unique(timedepvar(:,1));
 EventID = double(ismember(FundID,DropReason(:,1)));  % Finding those liquidated funds
    %-- Find DropID 0 = Alive; Others = Reasons of drop
 DropID = zeros(length(FundID),1);
 for i = 1:length(FundID)
     idx = find(DropReason(:,1)==FundID(i,1));
     if length(idx)~=0
         DropID(i,1)=DropReason(idx,2);
     else
         DropID(i,1)=0;
     end
 end
 Characters = [FundID EventID DropID];             
% timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] % 
b=1;
counter=0;
while b<=size(timedepvar,1)
    counter=counter+1;
    f=find(timedepvar(:,1)==timedepvar(b,1)); % Time dependent variables
    F=find(Characters(:,1)==timedepvar(b,1)); % Character variables
    Char=Characters(F,:);
    temp=timedepvar(f,:);   % [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    numint=length(f);                         % Number of years
    for t=1:numint
        Dist1(t)=temp(t,3); % Distance1
        Dist2(t)=temp(t,4); % Distance2
        Ret  (t)=temp(t,5); % Fund return
        Volat(t)=temp(t,6); % Fund volatility
        Aum  (t)=temp(t,7); % fund Size
        Flow (t)=temp(t,8); % Fund Flow
        VIX(t)  =temp(t,9); % VIX
        CSprd(t)=temp(t,10); % BAA10YM
        AggLq(t)=temp(t,11); % AggLiq
        InnLq(t)=temp(t,12); % InnovLiq
        TrdLq(t)=temp(t,13); % TradeLiq
        CRSP(t) =temp(t,14); % CRSP return
        TimeDep(1,1+(t-1)*13:t*13)=[t Dist1(t) Dist2(t) Ret(t) Volat(t) Aum(t) Flow(t) VIX(t) CSprd(t) AggLq(t) ...
                                      InnLq(t) TrdLq(t) CRSP(t)]; % Total 12 number of time-varyingvariables     
    end        
    container{counter}=[Char temp(1,2)-1992 numint TimeDep]; % Year 1992 is set to be the origin year
                  % [FundID EventID DropID numint(Dur/upper) t timedepvar]       
    f=[]; F=[]; Char=[]; temp=[]; TimeDep=[]; 
    Dist1=[]; Dist2=[]; Ret=[]; volat=[]; Aum=[]; Flow=[];
    VIX=[]; CSprd=[]; AggLq=[];
    InnLq=[]; TrdLq=[]; CRSP=[];
    b=b+numint;
end
%Stack the datasets, container into one dataset
Result=[];
for i=1:length(container)
    d=container{i};
    Result=padconcatenation(Result,d,1);
    d=[]; 
end

for j=1:size(Result,1)
    if Result(j,2)==1
        lower(j,1)=Result(j,5)-0.5; % lower duration for dead funds
    else
        lower(j,1)=Result(j,5);
    end
end
 
ResultData=[Result(:,1) Result(:,5) Result(:,2:4) lower Result(:,5:end)];
          %[FoFID numint EventID DropID Year1992 lower numint(upper) t timevarying]

xlswrite('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\YearTrend\SAS4AML_YearTrend.xlsx',ResultData);

 
 






 


