clc
clear
timedepvar = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FoFData4SAS.xlsx');
    % timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    % This dataset is generated by using AliveDistanceLiquidation_FoF.m
DR = timedepvar(:,3)./timedepvar(:,4); % Distance ratio
% SharpeRatio = timedepvar(:,5)./timedepvar(:,6);
% SharpeRatio(isinf(SharpeRatio)|isnan(SharpeRatio)) = 0; % Replace NaNs and infinite values with zeros
U = unique(timedepvar(:,2));% Unique years
U(1)=[];                    % Delete 1992
for  k = 1:length(U)-1
    f = timedepvar(:,2)==U(k);
    DistanceRatio = DR(f);
    n = length(DistanceRatio);
    FundID = timedepvar(f,1);     % FundID
    % Step 2: Sort into quartiles
    [~, idxSorted] = sort(DistanceRatio,'descend');
    quartileIdx = zeros(n,1);
    % quartileSize = floor(n/4);
    % quartileIdx(idxSorted(1:quartileSize)) = 1;
    % quartileIdx(idxSorted(quartileSize+1:2*quartileSize)) = 2;
    % quartileIdx(idxSorted(2*quartileSize+1:3*quartileSize)) = 3;
    % quartileIdx(idxSorted(3*quartileSize+1:end)) = 4;
    quartileSize = floor(n/10);
    for t = 1:10
        quartileIdx(idxSorted((t-1)*quartileSize+1:t*quartileSize)) = t;
    end
    
    FundIDSorted = FundID(idxSorted);
    FundIDNextYear = timedepvar(timedepvar(:,2)==U(k+1),1);
    ReturnsNextYear = timedepvar(timedepvar(:,2)==U(k+1),5);

    for j = 1:length(FundIDNextYear)
        [~,b]=ismember(FundIDSorted,FundIDNextYear(j,1)); % Find if a fund in year+1 being in year
        if sum(b)>0
            Idx(j,1) = quartileIdx(find(b));
        else
            Idx(j,1) = 0; 
        end
    end
        
    % Step 3: Compute average return for each percentile (quartile) each year
    for i = 1:10
        avgReturns(k,i) = median(ReturnsNextYear(Idx == i));
    end
    f=[]; DistanceRatio=[];ReturnsNextYear=[];idxSorted=[];quartileIdx=[];
    FundID=[]; FundIDNextYear=[] ; FundIDSorted=[]; Idx=[];
end
[mean(avgReturns);median(avgReturns)]
bar3(avgReturns)
colorbar
cb = colorbar;  % Get the colorbar handle
cb.Ticks = 1:10;  % Set tick locations to match percentile bins
cb.TickLabels = { '100th prctile ' ...
    '90th prctile', ...
    '80th prctile', ...
    '70th prctile', ...
    '60th prctile', ...
    '50th prctile', ...
    '40th prctile', ...
    '30th prctile', ...
    '20th prctile', ...
    '10th prctile', ...
    ' '};

ylabel('Year')
years = 1994:2021;
ytick_positions = find(mod(years,2)==0);  % Label even years only
ytick_labels = cellfun(@(y) y(end-1:end), cellstr(string(years(ytick_positions))), 'UniformOutput', false);
yticks(ytick_positions);
yticklabels(ytick_labels);

xlabel('Distance Percentile')
zlabel('Ex-ante Returns')
title('Figre 4b: Sorting by Distance Ratio: Ex-ante Returns')
xticks(1:10);                         % Ensure the correct ticks are set
xticklabels(string(10:-1:1));         % Reverse the label order
ax = gca;
ax.XTickLabelRotation = 0;            % Make labels parallel to x-axis

% Caculating exante Returns over the whole smaple period for lowest vs. highest decile
CumRL = 1; % Assuming $1 dollar
CumRH = 1; 
for t = 1:size(avgReturns,1)
    CumRL = CumRL*(1+avgReturns(t,1));
    CumRH = CumRH*(1+avgReturns(t,10));
end
Profit = (CumRH-CumRL)*12;
% % Step 4: t-test between top (Q4) and bottom (Q1) quartiles
% group1 = ReturnsNextYear(quartileIdx == 1);
% group4 = ReturnsNextYear(quartileIdx == 4);
% 
% [h, p, ci, stats] = ttest2(avgReturns(3:end,1), avgReturns(3:end,4));
% 
% fprintf('\nT-test between Q1 and Q4 returns:\n');
% fprintf('t-statistic = %.4f, p-value = %.4f\n', stats.tstat, p);
% fprintf('95%% CI for difference = [%.4f, %.4f]\n', ci(1), ci(2));
