%================================================================================================================================%
%    This code is to compare the predition ability the Cox PH models by using the distance (FCM + GRANN) + performance variables                   
%================================================================================================================================%
timedepvar = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FoFData4SAS.xlsx');
    % timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    % This dataset is generated by using AliveDistanceLiquidation_FoF.m
timedepvar(:,9:end)=[];
DDM = timedepvar(:,3)./timedepvar(:,4);
timedepvar = [timedepvar(:,1:2) DDM timedepvar(:,5:8)]; % timedepvar= [FoFID Year DDM Return STD AUM Flow]
 %-- Liquidated Funds Drop Reasons
 DropReason = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FundDropReasons.xlsx','DropReasons');
    % DropReason = [DropFundID DropReasonID]
    %-- Find EventID 0 = Alive; 1 = Liquidated
 FundID = unique(timedepvar(:,1));
 EventID = double(ismember(FundID,DropReason(:,1)));  % Finding those liquidated funds
    %-- Find DropID 0 = Alive; Others = Reasons of drop
 DropID = zeros(length(FundID),1);
 for i = 1:length(FundID)
     idx = find(DropReason(:,1)==FundID(i,1));
     if length(idx)~=0
         DropID(i,1)=DropReason(idx,2);
     else
         DropID(i,1)=0;
     end
 end
 Characters = [FundID EventID DropID];   
 
b=1;
counter=0;
while b<=size(timedepvar,1)
    counter=counter+1;
    f=find(timedepvar(:,1)==timedepvar(b,1)); % Time dependent variables
    F=find(Characters(:,1)==timedepvar(b,1)); % Character variables
    Char=Characters(F,:);
    numint=length(f);               % Number of years
    if numint>1
        %temp=mean(timedepvar(f,3:7));   % mean([DDM Return STD AUM Flow]) %
        temp=timedepvar(f(end),3:7);
    else
        temp=timedepvar(f,3:7);
    end      
    DATA(counter,:)=[Char numint temp];
                  % [FundID EventID DropID Dur DDDM Return STD AUM Flow]       
    f=[]; F=[]; Char=[]; temp=[]; 
    b=b+numint;
end

TDATA=DATA(DATA(:,4)>=25,:); %Those duration larger thand 25 years are treated as training sample 

%== Now we calculate survival probabliity for every fund in the boostrap simulated holdout sample ==% 
%-- The conditional survival probability is shown in Equation (8.5) on pager 258.
N=1000;   % Number of Bootstrap simulations
for jj = 1:N
    inds = unidrnd(length(DATA),length(DATA),1);    % Bootstrap resample indices
    h = floor(length(inds)*0.5); % Houldout sample = 50% 
    temp = [DATA(inds(1:h),:); TDATA];
    C(:,1) = 1-temp(:,2);        % Liquidation variable. For CoxPH, 0 = EventHappend; 1 = Censored
    C(:,2) = temp(:,4);          % Fund duration.
    C(:,3:7) = temp(:,5:9);     % Fund Distance + Performance variables
    
    temp1=[DATA(inds(h+1:end),:)]; % Training sample
    D(:,1) = 1-temp1(:,2);       % Liquidation variable.
    D(:,2) = temp1(:,4);         % Duration.
    D(:,3:7) = temp1(:,5:9);    % Fund Distance + Performance
    % D = [EventID Dur Distance1 Distance2 Return STD AUM Flow]
    clear temp temp1
    L=length(D);
    [Coef_CHAR,LogL1,H1,STATS_CHAR]=coxphfit([D(:,4:5) log(D(:,6)) D(:,7)],D(:,2),'censoring',D(:,1)); % CoxPH estimatin for Performance variables
     coef_find1=find(abs(STATS_CHAR.z)>0);  % Find significant coefficients at 1% significant level
    [Coef_DIST,LogL2,H2,STATS_DIST]=coxphfit([D(:,3) D(:,4:5) log(D(:,6)) D(:,7)],D(:,2),'censoring',D(:,1)); % CoxPH estimatin for fund distance
     coef_find2=find(abs(STATS_DIST.z)>0);  % Find significant coefficients at 1% significant level    
    % Calculate CUMulative baseline HAZARD H0(t) based on Training sample.
    % Reference: 'Modelling Survival Data in Medical Research' (2nd Edition) Eq.(8.3), i.e., Nelson-Aalen estimate.
    Attrit_dur=D((D(:,1)==1),2);
    unique_dur=[0; unique(Attrit_dur)];
    H_CHAR(1) = 0;
    H_DIST(1) = 0;
    for i=2:length(unique_dur)
        R=D; % [FundID EventID Dur Distance1 Distance2 Return STD AUM Flow]
        f=find(D(:,2)>=unique_dur(i-1,1) & D(:,2)<unique_dur(i,1));
        FD=find(D(f,1)==1);
        d=length(FD); % The number of events between two distince event time t(i-1) and t(i).
        FR=find(D(:,2)>=unique_dur(i-1,1) & D(:,2)<unique_dur(i,1) & D(:,1)==1);
%         fR_1=find(D(:,2)<unique_dur(i-1,1) & D(:,1)==1); % Prepare to delete those who has already expereinced the event.
%         FR=[FR;fR_1];
        R(FR,:)=[];   % Risk set including all individuals who are at risk at time t(i).
         LR=length(R);
        R_CHAR = [R(:,4:5) log(R(:,6)) R(:,7)];
        R_DIST = [R(:,3) R(:,4:5) log(R(:,6)) R(:,7)];
        for j = 1:size(R,1)
            R1 = R_CHAR(j,:);
            X_CHAR(j) = exp((Coef_CHAR(coef_find1))'*(R1(coef_find1))');     % Cox regression for fund characteristics 
            R2 = R_DIST(j,:);
            X_DIST(j) = exp((Coef_DIST(coef_find2))'*(R2(coef_find2))');     % Cox regression for fund distance 
        end
        H_CHAR(i)=H_CHAR(i-1)+d/sum(X_CHAR); % Nelson-Aalen cumulative hazard estimate, eq(8.3) p.257
        H_DIST(i)=H_DIST(i-1)+d/sum(X_DIST);
    end
     LC=length(C);
     C_CHAR = [C(:,4:5) log(C(:,6)) C(:,7)];
     C_DIST = [C(:,3) C(:,4:5) log(C(:,6)) C(:,7)];
    for k=1:length(C)
        C1=C_CHAR(k,:);
        if floor(C(k,2))<=length(H_CHAR)-1
            C(k,2)=C(k,2);
        else
            C(k,2)=length(H_CHAR)-1; % For some reasons, xome C(k,2)>length(H_CHAR)
        end
        P_cox(k)=1-exp(-(H_CHAR(floor(C(k,2))+1)-H_CHAR(floor(C(k,2))))*exp((Coef_CHAR(coef_find1))'*(C1(coef_find1))')); % Cox regression  
        C2=C_DIST(k,:);
        PD_cox(k)=1-exp(-(H_DIST(floor(C(k,2))+1)-H_DIST(floor(C(k,2))))*exp((Coef_DIST(coef_find2))'*(C2(coef_find2))')); % Cox regression
    end
    [fp_1, tp_1,~,auc_1] = perfcurve(C(:,1),P_cox',0);
    TP_1{jj} = tp_1;
    FP_1{jj} = fp_1;
    AUC1(jj) = auc_1;
    [fp_2, tp_2,~,auc_2] = perfcurve(C(:,1),PD_cox',0);
    TP_2{jj} = tp_2;
    FP_2{jj} = fp_2;
    AUC2(jj) = auc_2;

    C=[]; D=[]; P_cox=[]; PD_cox=[];
    tp_1=[]; fp_1=[]; auc_1=[];
    H_CHAR=[];C_CHAR=[];
    coef_find1=[];
    C1=[];R1=[];X_CHAR=[];
    
    tp_2=[]; fp_2=[]; auc_2=[];
    H_DIST=[];C_DIST=[];
    coef_find2=[];
    C2=[];R2=[];X_DIST=[];
end
   
for m=1:N
    ttp1(1:size(TP_1{m},1),m)=TP_1{m};
    ffp1(1:size(FP_1{m},1),m)=FP_1{m};
    
    ttp2(1:size(TP_2{m},1),m)=TP_2{m};
    ffp2(1:size(FP_2{m},1),m)=FP_2{m};
end

figure(2)

plot(sort(mean(ffp1,2)),sort(mean(ttp1,2)),'r')
hold on
plot(sort(mean(ffp2,2)),sort(mean(ttp2,2)),'g+')
hold off
% AUC_cox = auroc(sort(mean(ffp1,2)),sort(mean(ttp1,2)))
% AUC_endo = auroc(sort(mean(ffp2,2)),sort(mean(ttp2,2)))
xlabel('False postive rate')
ylabel('True positive rate')
title('Figure 3: Predictive Power with/without Dependence Distance Metric ')
legend(['  Fund Performance Only           AUC = ' num2str(mean(AUC1))],['Distance + Fund Performance    AUC = ' num2str(mean(AUC2))])




  

    

    








    
    
    
    
    











    
