%--------------------------------------------------------------%
%== The following code is to compare statistics DDM for FoFs ==%
%--------------------------------------------------------------%

timedepvar = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FoFData4SAS.xlsx');
    % timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    % This dataset is generated by using AliveDistanceLiquidation_FoF.m
 %-- Liquidated Funds Drop Reasons
 DropReason = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FundDropReasons.xlsx','DropReasons');
    % DropReason = [DropFundID DropReasonID]
    %-- Find EventID 0 = Alive; 1 = Liquidated
 FundID = unique(timedepvar(:,1));
 EventID = double(ismember(FundID,DropReason(:,1)));  % Finding those liquidated funds
    %-- Find DropID 0 = Alive; Others = Reasons of drop
 DropID = zeros(length(FundID),1);
 for i = 1:length(FundID)
     idx = find(DropReason(:,1)==FundID(i,1));
     if length(idx)~=0
         DropID(i,1)=DropReason(idx,2);
     else
         DropID(i,1)=0;
     end
 end
 Characters = [FundID EventID DropID];             
% timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] % 
b=1;
counter=0;
while b<=size(timedepvar,1)
    counter=counter+1;
    f=find(timedepvar(:,1)==timedepvar(b,1)); % Time dependent variables
    F=find(Characters(:,1)==timedepvar(b,1)); % Character variables
    Char=Characters(F,:);
    temp=timedepvar(f,:);   % [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    numint=length(f);                         % Number of years
    container{counter}=[temp(:,1:9) [zeros(numint-1,1);Char(1,2)]];
                      % [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX EventID]       
    f=[]; F=[]; Char=[]; temp=[]; 
    b=b+numint;
end
%Stack the datasets, container into one dataset
Result=[];
for i=1:length(container)
    d=container{i};
    Result=padconcatenation(Result,d,1);
    d=[]; 
end
Result(Result(:,2)==1998,4) = Result(Result(:,2)==1998,4)*10;
% %-- Calculating the mean duration for live and liquidated FoFs --%
% b = 1;
% counter = 0;
% while b<=size(Result,1)
%     counter = counter + 1;
%     n = length(find(Result(:,1)==Result(b,1)));
%     Dur(counter,:) = [Result(b,1) n Result(b+n-1,end)]; %[FoFID Duration EventID]
%     b = b + n;
% end
% Stat_Dur = [mean(Dur(:,2)) median(Dur(:,2)) mean(Dur(Dur(:,3)==0,2)) mean(Dur(Dur(:,3)==1,2))]; 
%            %[MeanDur MedianDur MeanLiveDur MeanLiquidDur]

%-- Calculating the mean of DDM & compare DDM for live and liquidated each year --%
U = unique(Result(:,2)); % Unique years
U(1)=[];
for i = 1:length(U)
    f1 = find(Result(:,2)==U(i) & Result(:,end)==0); % Alive FoFs  for a year
    f2 = find(Result(:,2)==U(i) & Result(:,end)==1); % Liqui FoFs  for a year
    f  = find(Result(:,2)==U(i));                    % All   FoFs  for a year
    Stat(i,:) = [U(i) mean(Result(f1,3)./Result(f1,4)) mean(Result(f2,3)./Result(f2,4)) ...
                 ttest2(Result(f1,3)./Result(f1,4),Result(f2,3)./Result(f2,4)) mean(Result(f,3)./Result(f,4))];
             %[Year DDM_Alive DDM_Liquid Two-sample_t-test DDM_AllFoFs]
    f1=[];f2=[]; f=[];
end
figure(1)
bar(Stat(:,1),Stat(:,5))
ylabel('Distance Ratio')
xlabel('Year')
title('Figure 3a: Average Distance Ratio Over Sample Period')
[mean(Stat(:,2)) mean(Stat(2:end,3)) median(Stat(:,2)) median(Stat(2:end,3))]
% figure(2)
% bar(Stat(:,1),[Stat(:,2) Stat(:,3) Stat(:,5)],'stacked')
% ylabel('Dependence Distance Metric')
% xlabel('Year')
% title('Figure 2: Depdence Distance Metric Value Over the Sample Period')
% % figure(1)
% % hist(Result(:,3)./Result(:,4),100)
% % figure(2)
% %--how to set overflow value and make all values greater than it in one bar
% DDM = Result(:,3)./Result(:,4);
% [bin,edge] = histcounts(DDM,100);
% overflow_up = prctile(DDM,95);  % upper overflow
% lastBin = sum(bin(edge(2:end)>overflow_up));
% bar([bin(edge(2:end)<=overflow_up) lastBin]);
% % Then change the last x-tick label with:
% cut_ind = find(edge(1:end)<=overflow_up,1,'last');
% % xtlbls = cellstr(strcat('[',num2str(round(edge(1:cut_ind-1).')),...
% %     ',', num2str(round(edge(2:cut_ind).')),']'))
% xtlbls = cellstr(num2str(edge(1:cut_ind-1).'));
% xtlbls(end+1) = {['>' num2str(round(overflow_up))]};
% xtlbls=[xtlbls(1) xtlbls(7) xtlbls(14)   xtlbls(21) xtlbls(end)];
% xticklabels(xtlbls)
% title('Histogram of DDM')
% xlabel('DDM')
% ylabel('Number of FoF&Year')


 
 
 






 


