%--------------------------------------------------------------%
%== The following code is to compare statistics DDM for FoFs ==%
%--------------------------------------------------------------%

timedepvar = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FoFData4SAS.xlsx');
    % timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    % This dataset is generated by using AliveDistanceLiquidation_FoF.m
 %-- Liquidated Funds Drop Reasons
 DropReason = xlsread('C:\Users\ias05106\OneDrive - University of Strathclyde\Desktop\Updated Hedge Fund Project\FundDropReasons.xlsx','DropReasons');
    % DropReason = [DropFundID DropReasonID]
    %-- Find EventID 0 = Alive; 1 = Liquidated
 FundID = unique(timedepvar(:,1));
 EventID = double(ismember(FundID,DropReason(:,1)));  % Finding those liquidated funds
    %-- Find DropID 0 = Alive; Others = Reasons of drop
 DropID = zeros(length(FundID),1);
 for i = 1:length(FundID)
     idx = find(DropReason(:,1)==FundID(i,1));
     if length(idx)~=0
         DropID(i,1)=DropReason(idx,2);
     else
         DropID(i,1)=0;
     end
 end
 Characters = [FundID EventID DropID];             
% timedepvar= [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] % 
b=1;
counter=0;
while b<=size(timedepvar,1)
    counter=counter+1;
    f=find(timedepvar(:,1)==timedepvar(b,1)); % Time dependent variables
    F=find(Characters(:,1)==timedepvar(b,1)); % Character variables
    Char=Characters(F,:);
    temp=timedepvar(f,:);   % [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX BAA10YM AggLiq InnovLiq TradedLiq CRSP] %
    numint=length(f);                         % Number of years
    container{counter}=[temp(:,1:9) [zeros(numint-1,1);Char(1,2)]];
                      % [FoFID Year Distance1 Distance2 Return STD AUM Flow VIX EventID]       
    f=[]; F=[]; Char=[]; temp=[]; 
    b=b+numint;
end
%Stack the datasets, container into one dataset
Result=[];
for i=1:length(container)
    d=container{i};
    Result=padconcatenation(Result,d,1);
    d=[]; 
end
Result(Result(:,2)==1998,4) = Result(Result(:,2)==1998,4)*10;
% %-- Calculating the mean duration for live and liquidated FoFs --%
% b = 1;
% counter = 0;
% while b<=size(Result,1)
%     counter = counter + 1;
%     n = length(find(Result(:,1)==Result(b,1)));
%     Dur(counter,:) = [Result(b,1) n Result(b+n-1,end)]; %[FoFID Duration EventID]
%     b = b + n;
% end
% Stat_Dur = [mean(Dur(:,2)) median(Dur(:,2)) mean(Dur(Dur(:,3)==0,2)) mean(Dur(Dur(:,3)==1,2))]; 
%            %[MeanDur MedianDur MeanLiveDur MeanLiquidDur]

%-- Calculating the mean of DDM & compare DDM for live and liquidated each year --%
% U = unique(Result(:,2)); % Unique years
% U(1)=[];
% for i = 1:length(U)
%     f1 = find(Result(:,2)==U(i) & Result(:,end)==0); % Alive FoFs  for a year
%     f2 = find(Result(:,2)==U(i) & Result(:,end)==1); % Liqui FoFs  for a year
%     f  = find(Result(:,2)==U(i));                    % All   FoFs  for a year
%     Stat(i,:) = [U(i) mean(Result(f1,3)./Result(f1,4)) mean(Result(f2,3)./Result(f2,4)) ...
%                  ttest2(Result(f1,3)./Result(f1,4),Result(f2,3)./Result(f2,4)) mean(Result(f,3)./Result(f,4))];
%              %[Year DDM_Alive DDM_Liquid Two-sample_t-test DDM_AllFoFs]
%     f1=[];f2=[]; f=[];
% end
% subplot(2,1,1)
% bar(Stat(:,1),Stat(:,5))
% ylabel('Dependence Distance Measure')
% xlabel('Year')
% title('Figure 2a: FoFs Depdence Distance Measures over Sample Period')
% [mean(Stat(:,2)) mean(Stat(2:end,3)) median(Stat(:,2)) median(Stat(2:end,3))]


% Alive = Stat(:,2); C = nan(length(Stat),1); Liquid = Stat(:,3);
% boxplot([Alive C Liquid])
% xticks([1,3])
% xticklabels(['Alive','Liquidated'])
% ylabel('Dependence Distance Measure')
% title('Figure 2b: Comparison of Dependence Distance Measure')
%---------------- KM Plot ----------- %
b=1;
counter=0;
while b<=size(Result,1)
    counter = counter + 1;
    n = length(find(Result(:,1)==Result(b,1)));
    KMdata(counter,:) = [n        Result(b+n-1,end) mean(Result(b:b+n-1,3)./Result(b:b+n-1,4))];
                       %[Duration Event             DDM]
    b = b + n;
end
for  i = 1:length(KMdata)
    if KMdata(i,3)<prctile(KMdata(:,3),50)
        Group{i,1} = 'High Distance Ratio';
%     elseif KMdata(i,3)>=prctile(KMdata(:,3),33) && KMdata(i,3)>=prctile(KMdata(:,3),66)
%         Group{i,1} = 'Medium DDM';
    else
        Group{i,1} = 'Low Distance Ratio';
    end
end
[p,fh,stats] = MatSurv(KMdata(:,1), KMdata(:,2), Group,'xlabel','Time (Years)', ...
                         'Title','Figure 3b: KM Survival Curves for Distance Ratio','RT_KMplot',1);



 
 
 






 


